---
### Copy over pfsense XML, remove config.cache, and reboot ###

- hosts: router
  gather_facts: false
  tasks:
  - name: Pause ONE minute to wait for pfSense creation
    pause:
      minutes: 1 #Edit to your desired time. It took less than a minute for my VM to spin up.
  - name: Ansible copy file to remote server
    copy:
      src: /etc/ansible/configs/config.xml #Directory where my config was stored
      dest: /cf/conf #pfsense directory which holds config.xml
  - name: Remove config.cache in tmp
    file:
      path: /tmp/config.cache
      state: absent
  - name: Reboot Machine
    reboot: